### ISSUE TITLE
Avif/Webp Support

### ISSUE THREAD

**Issue by JoyceBabu** [ChrisRega/image-compare#4]
Are avif/webp images supported?

**Comment by ChrisRega** [comment]
This crate only compares the decoded image byte arrays. The crate doing the actual decoding from files is this: [image-rs](https://github.com/image-rs/image) their support matrix looks like avif is supported for 8bit only in loading if `avif-decoder` is enabled in your loading code `cargo.toml` and wepb should work out of the box.
![grafik](https://github.com/ChrisRega/image-compare/assets/60792386/f17aaf41-e0c2-4eb5-963a-c7f5e514c531)
